### ISSUE TITLE
Add options to make deb files for qemu-user & qemu-user-static?

### ISSUE THREAD

**Issue by WheezyE** [Itai-Nelken/qemu2deb-RPi#11]
### A bit of homework 
- [x] I have read the README and other issues and PR's and my feature request is new or I have a new way to implement it (OK leave this checkbox blank, all feature requests are welcome!).
- [x] my feature request isn't something like: add support for  64bit. make this and that work. make magic. etc.

**Is your feature request related to a problem? Please describe.**
I'm trying to follow [Novaspirit's old guide](https://www.novaspirit.com/2019/04/15/run-x86-arm/) for running x86 wine apps on Pi using qemu, qemu-user, and qemu-user-static.  I've used his deb files and images to try to run wine apps in the past, but always got bus errors due to old qemu repo versions.

I've used your scripts to successfully build a new qemu from source (thank you!) and even used this to run Win98 using your VM scripts (also thank you, that is pretty cool and it was effortless).  Now, to follow Novaspirit's guide, I'm finding I need to compile my own qemu-user and qemu-user-static too.

**Describe the solution you'd like**
Would you may be be able to add options in your script to have it also compile and package debs for qemu-user and qemu-user-static?

**Describe alternatives you've considered**
I'm trying to follow [this guide to build my own qemu-user-static](http://logan.tw/posts/2018/02/18/build-qemu-user-static-from-source-code/) and am in the process of building/testing that right now, though I feel very much like I don't know quite what I'm doing.  If I eventually get things to build and install correctly, my next plan is to implement these steps for other users of a script I'm making.  I think it would be nice to have deb packages available for anybody who wanted them so that they could save a few hours of compiling time.

**Additional context**
I'm not actually even sure if Novaspirit's x86 on Pi guide will work for me yet (since none of his images or deb files on his Patreon worked for my purposes), but I'll hopefully get things installed/tested soon to see.

**Comment by WheezyE** [comment]
Ah yes, I'm a little out of my depth:
I ran
```

sudo dpkg -i qemu-6.0.50-armhf.deb # install pre-made qemu deb file (from ita script)

    cd ~/Downloads
    git clone https://git.qemu.org/git/qemu.git
    cd qemu
    ./configure \
        --prefix=$(cd ..; pwd)/qemu-user-static \
        --static \
        --disable-system \
        --enable-linux-user \
        --enable-sdl \
        --enable-opengl \
        --audio-drv-list=pa \
        --enable-kvm
    #make -j$CORES
    #sudo make install
    ninja -C build  || error "Failed to run ninja -C build'!"
    sudo ninja install -C build
    cd ../qemu-user-static/bin
    for i in *; do sudo cp $i $i-static; done
	
sudo apt-get install -y binfmt-support debootstrap binutils debian-keyring debian-archive-keyring

	cd ~
	sudo debootstrap --foreign --arch i386 stretch ./chroot-stretch-i386 http://ftp.us.debian.org/debian
	sudo mount -t sysfs sys ./chroot-stretch-i386/sys/
	sudo mount -t proc proc ./chroot-stretch-i386/proc/
	sudo mount --bind /dev ./chroot-stretch-i386/dev/
	sudo mount --bind /dev/pts ./chroot-stretch-i386/dev/pts/
	sudo mount --bind /dev/shm ./chroot-stretch-i386/dev/shm/

sudo cp ~/Downloads/qemu-user-static/bin/qemu-i386-static ./chroot-stretch-i386/usr/bin/
```
But running `sudo chroot ./chroot-stretch-i386/` results in an error (since I didn't properly install qemu-user: If I install qemu-user w/ apt, it will uninstall my compiled qemu and replace it with the old version, but that chroot command will work using the old qemu).

**Comment by WheezyE** [comment]
Oh huh, there are [binaries for qemu-i386-static here](https://github.com/multiarch/qemu-user-static/releases/). Not sure if that's the same as qemu-user, though I still can't run it...
Edit: These binaries ^^^ are older than our fresh qemu build - and I wonder if they aren't compatible with our fresh qemu build since they're old.

**Comment by WheezyE** [comment]
I've been scouting out some [more information about files included in qemu builds here](https://github.com/WheezyE/Winelink/blob/main/docs/experiments/pi4_qemu_installer_attempts.txt) to see which files I might be missing for my purposes

**Comment by WheezyE** [comment]
I'm still working on this on-and-off, but I'm suspecting that my problem may be stemming from my lack of binfmt setup after compiling my own qemu-user-static build (I think I need `/usr/libexec/qemu-binfmt/i386-binfmt-P` or something like that).  My next plan is to `dpkg-deb -R` the Debian repo's qemu-user-static.deb, qemu-user.deb, and qemu.deb to find what's running in their `postinst` scripts (I suspect it's running something like [qemu-binfmt-conf.sh](https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh) - I'm hoping the repo deb's postinit scripts will show me how to set up my own compiled build).

I also suspect that qemu.deb in the debian repo is empty and that "qemu-user.deb" is the repo equivalent to what your script is compiling.  This script is super slick too by the way - thank you for making it :)

**Comment by Itai-Nelken** [comment]
I'll try to add the option to compile `qemu-user-static` as well. I plan to add it along with the option to compile latest release or from git (what the script currently does).
sorry for not answering, this week is really full for me and I'm working on other stuff. I'll start working on this as soon as I have time.

**Comment by WheezyE** [comment]
No worries at all man, and no pressure.  I really appreciate you just even just putting on the to-do list and considering it.  I've been pretty busy too and have kind of just been able to tinker sporadically and post here partially as a way to make notes for myself too on where I last left off - also just in case you got to it before I did since I'm never sure the next time I'll get to.  I've got a day off coming up tomorrow though and will hopefully be able to scout ahead a bit more.

**Comment by WheezyE** [comment]
Alright, so I was able to test things on my Pi4, but still got the "Bus error" that everybody else got in Novaspirit tech's install method when trying to run winecfg.
1. I used `sudo apt install -y` to install an a v3.1 "`qemu`" (blank container), `qemu-user`, and `qemu-user-static` from the debian repo.
2. Then I used `sudo rm /usr/bin/qemu-*static` to delete the qemu-*-static files that were installed (since the computer wouldn't let me overwrite them while they were in use).
3. Then I copied my compiled v6.0.50 `qemu-user-static` files and the v6.0.50 compiled `qemu-user` files that your script made to `/usr/`...
4. I then followed [these steps](https://github.com/WheezyE/Winelink/blob/main/docs/pi4_qemu_installer_attempts.txt) (also linked above) to do Novaspirit's guide.

I guess in the end, I don't really need qemu-user-static since it's not really working for my purposes.  I guess we can close this issue.

I did learn in the process though that the conflicts listed in your script will prevent other users from installing qemu-user-static .deb files even though those shouldn't actually conflict with the packages that your script compiles.

**Comment by Itai-Nelken** [comment]
all the conflicting packages I my script uses where added because the deb would fail to install otherwise...
Close this issue if you want, anyway I'll try to add the option to compile only the part of qemu you need to the script.
thanks for the idea!

**Comment by WheezyE** [comment]
As a side note: I got around the bus error this morning simply by restarting my pi and trying again (strange - might be binfmt not being active).  The apt packages were required in order to set up binfmt (or something) using the postinst script for qemu-user-static.  Anyway, I do appreciate your thoughts and looking into it. Thank you again!

**Comment by Itai-Nelken** [comment]
can you comment the `postinst` script of qemu-user-static from the repos please?

**Comment by WheezyE** [comment]
Sure thing.  Only the `qemu-user-static` & `qemu-user-binfmt` repo .deb's have `postinst` scripts (the `prerm` scripts in each .deb are identical to the `postinst` scripts).  Those two .deb's `postinst` scripts are almost identical (basically just the deb package name in the script changes).  Here's the `postinst` script from `qemu-user-static`:
```bash
#!/bin/sh
set -e
# check if we're running inside an (lxc) container
# (we may copy or move this to the postinst script too, to skip installing it)
grep -zqs ^container= /proc/1/environ && exit 0

# == binfmt registration/deregistration ==
if command -v update-binfmts > /dev/null ; then

fmts="aarch64 alpha arm armeb cris hppa i386 m68k microblaze mips mipsel mipsn32 mipsn32el mips64 mips64el ppc ppc64 ppc64abi32 ppc64le riscv32 riscv64 s390x sh4 sh4eb sparc sparc32plus sparc64 x86_64 xtensa xtensaeb"

# linux ELF_OSABI(byte7) can be 0 (traditional,SYSV) or 3 (GNU/LINUX extensions)
# binfmt registration does not allow a enum, only value&mask.  So we use broader mask
# to allow both 0 and 3 here, this also lets 1 (HPUX) and 2 (NETBSD) - 0xfc not 0xff
# alternative is to create 2 magic/mask pairs instead of one

    aarch64_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7\x00'
     aarch64_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
      alpha_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x26\x90'
       alpha_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
        arm_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00'
         arm_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
      armeb_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28'
       armeb_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
       cris_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x4c\x00'
        cris_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
       hppa_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x0f'
        hppa_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
       i386_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00'
        i386_mask='\xff\xff\xff\xff\xff\xfe\xfe\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
       m68k_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x04'
        m68k_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
 microblaze_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\xba\xab'
  microblaze_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
       mips_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08'
        mips_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
     mipsel_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08\x00'
      mipsel_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
     mips64_magic='\x7f\x45\x4c\x46\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08'
      mips64_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
   mips64el_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08\x00'
    mips64el_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xfe\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
        ppc_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x14'
         ppc_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
      ppc64_magic='\x7f\x45\x4c\x46\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15'
       ppc64_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
 ppc64abi32_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15'
  ppc64abi32_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
    ppc64le_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15\x00'
     ppc64le_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\x00'
    riscv32_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xf3\x00'
     riscv32_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
    riscv64_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xf3\x00'
     riscv64_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
      s390x_magic='\x7f\x45\x4c\x46\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x16'
       s390x_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
        sh4_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x2a\x00'
         sh4_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
      sh4eb_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x2a'
       sh4eb_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
      sparc_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x02'
       sparc_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
sparc32plus_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x12'
 sparc32plus_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
    sparc64_magic='\x7f\x45\x4c\x46\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x2b'
     sparc64_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
     x86_64_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00'
      x86_64_mask='\xff\xff\xff\xff\xff\xfe\xfe\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
     xtensa_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x5e\x00'
      xtensa_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
   xtensaeb_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x5e'
    xtensaeb_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'


# find which fmts needs to be filtered out, which is arch-dependent.
# Drop support for emulating amd64 on i386, http://bugs.debian.org/604712
case "$DPKG_MAINTSCRIPT_ARCH" in
  amd64 | i386) omit="i386|x86_64" ;;
  arm | armel | armhf | arm64) omit="arm|aarch64" ;;
  mips | mipsel) omit="$DPKG_MAINTSCRIPT_ARCH" ;;
  ppc64 | powerpc) omit="ppc|ppc64|ppc64abi32" ;;
  ppc64el) omit="ppc64le" ;;
  s390x) omit="s390x" ;;
  sparc | sparc64) omit="sparc|sparc32plus|sparc64" ;;
  *) omit="$DPKG_MAINTSCRIPT_ARCH" ;;
esac

remove_binfmt() {
    if [ -f /var/lib/binfmts/qemu-$1 ]; then
	update-binfmts --package qemu-user-static --remove qemu-$1 /usr/bin/qemu-$1-static
    fi
}

case "$DPKG_MAINTSCRIPT_NAME:$1" in

    postinst:configure)
	for fmt in $fmts ; do

	    eval "case $fmt in $omit) magic= ;; *) magic=\"\$${fmt}_magic\" mask=\"\$${fmt}_mask\" ;; esac"
	    if [ -n "$magic" ]; then
		update-binfmts --package qemu-user-static --install qemu-$fmt /usr/bin/qemu-$fmt-static \
			--magic "$magic" --mask "$mask" --offset 0 --credential yes --fix-binary yes
	    else
		remove_binfmt $fmt
	    fi
	done
	;;

    prerm:remove)
	for fmt in $fmts ; do
	    remove_binfmt $fmt
	done
	;;

esac

fi
# == binfmt registration/deregistration ==
```
This v3.1 binfmt setup code might be related to [qemu-binfmt-conf.sh](https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh)(?)

The instructions for [qemu-user-static suggest setting up binfmt](https://wiki.debian.org/RaspberryPi/qemu-user-static#Setting_up_the_host) for the qemu-ARCHITECTURE-static binary that a user chooses to run in their particular chroot instance.  I believe that this postinst script alone may comprise the entire `qemu-user-binfmt` .deb file (since `qemu-user-static` is said to provide `qemu-user-binfmt` and the entire `qemu-user-binfmt` .deb only seems to contain this postinst script and some documents).

Here are some other links too where you can download those packages to `dpkg-deb -R` them if you like
 - [qemu](https://packages.debian.org/buster/armhf/qemu) (buster) v3.1 _<-- empty: contains copyright and changelogs only (no binaries)_
 - [qemu-user](https://packages.debian.org/buster/armhf/qemu-user) (buster) v3.1 _<-- The repo package has no postinst script.  This package seems to be the same thing that your script compiles (just way older than your script's fresh binaries)._
 - [qemu-user-static](https://packages.debian.org/buster/armhf/qemu-user-static) (buster) v3.1 (provides qemu-user-binfmt v3.1) _<-- Contains qemu-*-static binaries, documents, and postinst/prerm scripts.  Turns out all I really needed for my purposes was qemu-i386-static, but other qemu-ARCHITECTURE-static binaries are in this package too_
 - [qemu-user-binfmt](https://packages.debian.org/buster/armhf/qemu-user-binfmt) (buster) v3.1 _<-- Contains no binaries, just some doc files and postinst/prerm scripts._
 - [binfmt-support](https://packages.debian.org/buster/armhf/binfmt-support) _<-- Looks like it's its own thing (not related to qemu, but helps qemu)_

Edit: I also [just learned](https://en.wikipedia.org/wiki/Binfmt_misc) that binfmt_misc registers config files into `/proc/sys/fs/binfmt_misc/`  (and also into `/usr/lib/binfmt.d` & `/etc/binfmt.d/`) and it's kind of blowing my mind.

**Comment by Itai-Nelken** [comment]
Thanks!

**Comment by WheezyE** [comment]
I've explored qemu-user-static a bit more and still think it's probably not going to work for wine how I would like it to (so this feature request is not really needed for me anymore), but I learned a lot and wanted to share some stuff I learned in the process:

The file `qemu-i386-static` seems to be the i386 userspace (?) emulator within the deb package called "qemu-user-static".  I'm still not sure if it depends on the regular qemu binaries, but I think it may not.

This commit of qemu-i386-static seems to kind of work for running an x86 chroot on Pi 4.
 _Some newer and older commits either won't run wine at all ("Bus error") or will give me more "Illegal instruction" errors (and then crash) (after saying "qemu-i386-static: ../accel/tcg/translate-all.c:2724: page_set_flags: Assertion `start < end' failed")._
```
    # Compile and build qemu-user-static (qemu-i386-static)
    cd ~/Downloads
    git clone https://git.qemu.org/git/qemu.git
    cd qemu
	git checkout 79d6f2baa4b738bb223a0ad382661fe501b0c867
    ./configure --prefix=$(cd ..; pwd)/qemu-user-static --static --disable-system --enable-linux-user --target-list=i386-linux-user --disable-tools # Pinebook guide
    # The "--target-list=i386-linux-user" variable builds just qemu-i386-user
    #make -j$CORES && sudo make install # slower build method
    ninja -C build
    sudo ninja install -C build
    cd ../qemu-user-static/bin
    for i in *; do sudo mv $i $i-static; done
```

The `qemu-i386-static` file we built from qemu-user-static should then be copied to `/usr/bin/` and then registered into binfmt: 
```
sudo rm /usr/bin/qemu-i386-static # use this command if you already have an older version of qemu-user-static installed (otherwise you will get 'file in use' error when trying to copy your newly build qemu-i386-static file to /usr/bin/)
sudo cp ~/qemu-user-static/bin/qemu-i386-static /usr/bin/
# sudo cp ~/qemu-user-static/bin/qemu-i386-static ~/chroot-stretch-i386/usr/bin/ # use this command if you have a chroot jail on your non-i386 system that you want to use to run i386 files

sudo systemctl restart systemd-binfmt # Reset any files cached within /proc/sys/fs/binfmt_misc/ ? This command will make the computer reload any config files (config files are stored in /usr/lib/binfmt.d or /etc/binfmt.d/ ) in order to use them to make temp cached files within /proc/sys/fs/binfmt_misc/ . I think that if there are no config files then temp files will not be reloaded or destroyed.

# i386 variables
# These commented magic & mask vars are from https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh but don't seem to work (result in only "Illegal instruction" errors when trying to run winecfg)
magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00'
#magic='\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00'
mask='\xff\xff\xff\xff\xff\xfe\xfe\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
#mask='\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
fmt=i386

# Remove old qemu-i386-static binfmt registration (removes cached temp binfmt file within /proc/sys/fs/binfmt_misc/ )
sudo /usr/sbin/./update-binfmts --package qemu-user-static --remove qemu-$fmt /usr/bin/qemu-$fmt-static

#binfmt qemu-ARCHITECTURE-static registration (adds cached temp binfmt file within /proc/sys/fs/binfmt_misc/ )
sudo /usr/sbin/./update-binfmts --package qemu-user-static --install qemu-$fmt /usr/bin/qemu-$fmt-static \
        --magic "$magic" --mask "$mask" --offset 0 --credential yes --fix-binary yes
```

I've mentioned a config file in the second code block above that will auto-cache binfmt magic into /proc/sys/fs/binfmt_misc/ on reboot or whenever we run `sudo systemctl restart systemd-binfmt`.  That config file is below and I _think_ should be stored in `/usr/lib/binfmt.d/` (though maybe `/etc/binfmt.d/` instead - or either location?):
```
# qemu-i386-static.conf
:qemu-i386:M::\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00:\xff\xff\xff\xff\xff\xfe\xfe\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-i386-static:
```

Part of my wonders if I could get winecfg and winetricks to work better with less "Illegal instruction" errors if I had the right magic/mask filters for wine.  I also think that the binfmt config files might be those extra files in the debian repo deb files.

There's a little bit more info at these links: 
 - https://github.com/WheezyE/Winelink/blob/main/docs/experiments/pi4_qemu_installer_attempts.txt
 - https://github.com/WheezyE/Winelink/blob/main/docs/experiments/Pi4_qemu_installer_testing.sh
 - https://forum.pine64.org/showthread.php?tid=8979 (A modified version of novaspirit's guide that has some extra tips)


Edit: I noticed box86's binfmt config file used a different mask to find i386 files, but that magic/mask combo doesn't work for qemu-user-static running winecfg either:
```
# /etc/binfmt.d/box86.conf
:x86:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/local/bin/box86:
```
I copied the magic/mask over to qemu-i386-static.conf, but no luck

**Comment by Itai-Nelken** [comment]
Thanks a lot!

**Comment by WheezyE** [comment]
Just wanted to correct some info I wrote down above for anybody googling info: I came back to this thread to copy-pasta the magic/mask info for box86 and realized I had written them down a bit wrong above:  Correct box86 magic/mask and a better manual binfmtutils registration method here: https://github.com/termux/proot/issues/192
