### ISSUE TITLE
[not script related] qemu-x86_64 requires GLIBC_2.28 that is not available on jetson nano 

### ISSUE THREAD

**Issue by YahiyaHussain** [Itai-Nelken/qemu2deb-RPi#8]
I tried to install .deb on jetson nano which an arm64 system but after it finished when I tried running qemu-system-x86_64 it said it required GLIBC 2.28 . but it the system has GLIBC 2.27-3ubuntu1. Could this .deb support  GLIBC 2.27-3ubuntu1. My goal is to run a python package, cortex.dev which depends on x86 on the jetson nano since the jetson nano already has docker.
![image](https://user-images.githubusercontent.com/34356761/109923897-75971280-7c8d-11eb-8875-5ec025f25bc7.png)

**Comment by Itai-Nelken** [comment]
> I tried to install .deb on jetson nano which an arm64 system but after it finished when I tried running qemu-system-x86_64 it said it required GLIBC 2.28 . but it the system has GLIBC 2.27-3ubuntu1. Could this .deb support GLIBC 2.27-3ubuntu1. My goal is to run a python package, cortex.dev which depends on x86 on the jetson nano since the jetson nano already has docker.
> ![image](https://user-images.githubusercontent.com/34356761/109923897-75971280-7c8d-11eb-8875-5ec025f25bc7.png)

the script compiles QEMU using the official instructions (but using ninja for faster compiling).
I have no idea how to make it work.
 I will see if I can add `GLIBC_2.28`.

**Comment by Itai-Nelken** [comment]
you probably are on Ubuntu 18.04, right?
run this to make sure: `cat /etc/os-release`.

**Comment by Itai-Nelken** [comment]
you can also try to use the QEMU in the repos (if its there). `sudo apt install qemu-x86_64` I think.
I'm marking this issue as not script related because the cause is probably nvidia not making a newer OS for the jetson nano.

**Comment by Itai-Nelken** [comment]
@YahtzeeRage ?

**Comment by Itai-Nelken** [comment]
closing do to inactivity.<br>@YahtzeeRage you are welcome to reply and I'll reopen the issue.
